---
version: '2'
services:
    web1:
        image: nginx:latest
        container_name: aurora-web
        restart: always
        ports: 
            - "8008:8008"
        depends_on:
            - api
            - mysql 
        volumes:
            - /var/www:/var/www
            - ./nginx:/etc/nginx
        networks:
            - aurora_net

    api:
        image: grakiss/api:0.0.1
        container_name: aurora-api
        ports: 
            - "8009:8009"
        depends_on:
            - mysql
        networks:
            - aurora_net

    mysql:
        image: mariadb:10.2 
        container_name: aurora-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "3306" 
        volumes:
            - mysql_db:/var/lib/mysql
            - mysql_log:/var/log/mysql
        networks:
            - aurora_net
 
volumes:
    mongo_db:
    mysql_db:
    mysql_log:
networks:
    aurora_net:
